[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["cargo", "derive"] }
matches = "0.1.10"
chrono = "0.4.38"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
